services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: axum_db
    ports:
      - "5432:5432"
    healthcheck:
      test: ['CMD-SHELL', "psql -U admin -d axum_db -c 'SELECT 1'"]
      interval: 5s
      timeout: 3s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pg_admin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

  wait-for-db-to-test:
    image: hello-world
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
    driver: local
